// <auto-generated />
namespace InventoryManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class a9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a9));
        
        string IMigrationMetadata.Id
        {
            get { return "201512102359279_a9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
